"""A vehicle brief that a machine can check: every number carries its source.

WHY THIS EXISTS

We were handed an infographic, generated by an image model, captioned "these are
the textures". It was not textures. It was a plan, and it came with numbers:

    longitud = 13200      potencia = 2000      vel_max = 140     intro_year = 2009

Every one of them is plausible. Every one of them is wrong: the Renfe 465 is 2200
kW, 120 km/h, and entered service in 2004. Nothing about the picture looked like a
guess, and if those four numbers had gone into the .dat, the train would have been
wrong in a way that no test, no linter and no running game could ever have caught -
because a .pak full of confident nonsense compiles perfectly.

So the rule is not "be careful". The rule is mechanical:

    A NUMBER WITH NO SOURCE DOES NOT REACH THE .DAT.

and a source is one of four things, none of which is "a model said so":

    measured     a URL, a book, a works drawing - something a person can go and check
    reference    a pixel measurement of an image, with the image's sha256, so the
                 claim can be re-run (see tools/refmeasure.py)
    engine       a file:line in the Simutrans source - for the facts the game owns,
                 like which colour lights up at night
    derived      arithmetic over other facts in this spec, with the formula written
                 down. It inherits its inputs' sources, so it cannot launder them.

and a fifth, which is allowed but never silent:

    provisional  a guess. Prices, mostly. It builds, and every report says so out
                 loud, by name.

Anything else - "chatgpt", "ai", "the image", "obvious", "" - is refused, with the
Civia's four wrong numbers quoted back at you.

WHY THIS LIVES IN tools/ AND NOT IN core/

Because everything in core/ is shipped: tools/build_addon_zip.py packs `addon` and
`core` wholesale, so a module in core/ is a module in every artist's Blender. This
one names the models it refuses by name, and that list has no business being read by
a stranger downloading a sprite tool - it is a fact about how WE work, not a feature
of the add-on. So it stays here, next to refmeasure.py, on our side of the line.

The zip builder enforces this rather than trusting it: it refuses to write an archive
that carries any of these names. Move this file back into core/ and the build stops.
"""

import json
import re

KINDS = ("measured", "reference", "engine", "derived", "provisional")

# What people actually type when they mean "I made it up" or "a model told me".
# Refused by name, because the failure this module exists to stop was exactly this
# and it did not feel like a failure at the time - it felt like a head start.
#
# Matched as WORDS, not as prefixes: "railway" is not "ai", and a linter that thinks
# it is would be refusing citations for a living.
_NOT_A_SOURCE = ("ai", "chatgpt", "gpt", "llm", "claude", "copilot", "gemini",
                 "midjourney", "dall-e", "stable diffusion", "generated", "obvious",
                 "guess", "guessed", "assumed", "typical", "probably", "somewhere",
                 "i think", "looks about right")

_SHRUG = re.compile(r"\b(%s)\b" % "|".join(re.escape(w) for w in _NOT_A_SOURCE))


class SpecError(ValueError):
    pass


class Fact:
    """One number, and where it came from."""

    def __init__(self, key, value, kind, source, formula=None, note=None):
        self.key = key
        self.value = value
        self.kind = kind
        self.source = source
        self.formula = formula
        self.note = note

    @property
    def provisional(self):
        return self.kind == "provisional"

    def __repr__(self):
        return "%s=%r (%s: %s)" % (self.key, self.value, self.kind, self.source)


def _check_source(key, kind, source, formula):
    if kind not in KINDS:
        raise SpecError("%s: %r is not a kind of source. It must be one of: %s"
                        % (key, kind, ", ".join(KINDS)))

    if kind == "provisional":
        if not source:
            raise SpecError("%s: a provisional number still has to say WHY it is a "
                            "guess, so the report can quote it" % key)
        return

    if not source or not str(source).strip():
        raise SpecError(
            "%s has no source. A number with no source does not reach the .dat.\n"
            "  This rule is here because an AI-drawn infographic once handed us\n"
            "  longitud=13200, potencia=2000, vel_max=140, intro_year=2009 - four\n"
            "  confident, plausible, wrong numbers for a train whose real figures are\n"
            "  2200 kW, 120 km/h, 2004. A .pak full of nonsense compiles perfectly.\n"
            "  Give it a URL, a reference measurement, a file:line in the engine, a\n"
            "  formula - or mark it kind='provisional' and it will be listed as a guess."
            % key)

    hit = _SHRUG.search(str(source).strip().lower())
    if hit:
        raise SpecError(
            "%s: %r is not a source, it is a shrug (%r). A model that produces a "
            "number produces it in the same voice whether it read it off the "
            "builder's plate or invented it, and afterwards you cannot tell which - "
            "which is exactly how we nearly built a 2000 kW, 140 km/h Civia. Cite "
            "something a person can go and check, or mark it kind='provisional' and "
            "it will be listed as a guess."
            % (key, source, hit.group(1)))

    if kind == "derived" and not formula:
        raise SpecError("%s is derived, so write the formula down. Arithmetic whose "
                        "workings are lost is a guess wearing a lab coat." % key)


class Spec:
    """The brief. spec.value('speed') gives you a number you can defend."""

    def __init__(self, data, path=None):
        self.path = path
        self.data = data
        self.name = data.get("name")
        if not self.name:
            raise SpecError("the spec needs a name")
        self.pakset = data.get("pakset", "pak128")
        self.facts = {}

        for key, raw in (data.get("facts") or {}).items():
            if not isinstance(raw, dict) or "value" not in raw:
                raise SpecError("%s: write it as {\"value\": ..., \"kind\": ..., "
                                "\"source\": ...}, so the number and its provenance "
                                "cannot be separated" % key)
            kind = raw.get("kind", "measured")
            _check_source(key, kind, raw.get("source"), raw.get("formula"))
            self.facts[key] = Fact(key, raw["value"], kind, raw.get("source"),
                                   raw.get("formula"), raw.get("note"))

        self.cars = data.get("cars") or []

    def value(self, key, default=None):
        fact = self.facts.get(key)
        if fact is None:
            if default is not None:
                return default
            raise SpecError("%s: no such fact in the spec for %s. Add it with a "
                            "source, or pass a default." % (key, self.name))
        return fact.value

    def provisional(self):
        """Every guess in the spec, so a report can name them all."""
        return sorted((f for f in self.facts.values() if f.provisional),
                      key=lambda f: f.key)

    def sources(self):
        """{kind: [key, ...]} - the shape of what this spec is built on."""
        out = {}
        for fact in self.facts.values():
            out.setdefault(fact.kind, []).append(fact.key)
        return {k: sorted(v) for k, v in sorted(out.items())}

    def report(self):
        """The lines that go in the build report. Guesses last, and named."""
        lines = []
        for kind in KINDS:
            keys = self.sources().get(kind, [])
            if not keys:
                continue
            lines.append("%s (%d):" % (kind, len(keys)))
            for key in keys:
                f = self.facts[key]
                lines.append("    %-16s %-12s %s"
                             % (key, f.value, f.formula or f.source))
        return lines


def load(path):
    with open(path, encoding="utf-8") as f:
        try:
            data = json.load(f)
        except ValueError as e:
            raise SpecError("%s: not valid JSON: %s" % (path, e))
    return Spec(data, path)
