"""A vehicle brief that a machine can check: every number carries its source.

WHY THIS EXISTS

We were handed an infographic, generated by an image model, captioned "these are
the textures". It was not textures. It was a plan, and it came with numbers:

    longitud = 13200      potencia = 2000      vel_max = 140     intro_year = 2009

Every one of them is plausible. Every one of them is wrong: the Renfe 465 is 2200
kW, 120 km/h, and entered service in 2004. Nothing about the picture looked like a
guess, and if those four numbers had gone into the .dat, the train would have been
wrong in a way that no test, no linter and no running game could ever have caught -
because a .pak full of confident nonsense compiles perfectly.

So the rule is not "be careful". The rule is mechanical:

    A NUMBER WITH NO SOURCE DOES NOT REACH THE .DAT.

and a source is one of four things, none of which is "a model said so":

    measured     a URL, a book, a works drawing - something a person can go and check
    reference    a pixel measurement of an image, with the image's sha256, so the
                 claim can be re-run (see tools/refmeasure.py)
    engine       a file:line in the Simutrans source - for the facts the game owns,
                 like which colour lights up at night
    derived      arithmetic over other facts in this spec, with the formula written
                 down. It inherits its inputs' sources, so it cannot launder them.

and a fifth, which is allowed but never silent:

    provisional  a guess. Prices, mostly. It builds, and every report says so out
                 loud, by name.

Anything else - "chatgpt", "ai", "the image", "obvious", "" - is refused, with the
Civia's four wrong numbers quoted back at you.

AND THE SAME RULE FOR THE SPLITS

A six-car unit's .dat does not carry "178 seats", it carries six numbers that had
better add up to 178. Those per-car splits used to be literals in the asset's
Python, where spec.py never saw them - so the rule above guarded the totals and
nothing at all guarded the arithmetic under them. The 9000 shipped a payload split
summing to 186 against a measured 178, a whole car's worth of seats, and every
check passed, because nothing added them up.

So the cars live here too, and `car_totals` names the fact each column must sum to:

    "formation":  "Mc-R-M-M-R-Mc"          the shape: count, roles and order
    "car_totals": {"seats": "payload_seated", ...}   this column adds up to that fact
    "cars":       [{"key": ..., "seats": 28, ...}, ...]   in running order

A split that does not sum to its sourced total is not a spec, it is a rumour.

WHY THIS LIVES IN tools/ AND NOT IN core/

Because everything in core/ is shipped: tools/build_addon_zip.py packs `addon` and
`core` wholesale, so a module in core/ is a module in every artist's Blender. This
one names the models it refuses by name, and that list has no business being read by
a stranger downloading a sprite tool - it is a fact about how WE work, not a feature
of the add-on. So it stays here, next to refmeasure.py, on our side of the line.

The zip builder enforces this rather than trusting it: it refuses to write an archive
that carries any of these names. Move this file back into core/ and the build stops.
"""

import json
import re

KINDS = ("measured", "reference", "engine", "derived", "provisional")

# What people actually type when they mean "I made it up" or "a model told me".
# Refused by name, because the failure this module exists to stop was exactly this
# and it did not feel like a failure at the time - it felt like a head start.
#
# Matched as WORDS, not as prefixes: "railway" is not "ai", and a linter that thinks
# it is would be refusing citations for a living.
_NOT_A_SOURCE = ("ai", "chatgpt", "gpt", "llm", "claude", "copilot", "gemini",
                 "midjourney", "dall-e", "stable diffusion", "generated", "obvious",
                 "guess", "guessed", "assumed", "typical", "probably", "somewhere",
                 "i think", "looks about right")

_SHRUG = re.compile(r"\b(%s)\b" % "|".join(re.escape(w) for w in _NOT_A_SOURCE))


class SpecError(ValueError):
    pass


class Fact:
    """One number, and where it came from."""

    def __init__(self, key, value, kind, source, formula=None, note=None):
        self.key = key
        self.value = value
        self.kind = kind
        self.source = source
        self.formula = formula
        self.note = note

    @property
    def provisional(self):
        return self.kind == "provisional"

    def __repr__(self):
        return "%s=%r (%s: %s)" % (self.key, self.value, self.kind, self.source)


def _check_source(key, kind, source, formula):
    if kind not in KINDS:
        raise SpecError("%s: %r is not a kind of source. It must be one of: %s"
                        % (key, kind, ", ".join(KINDS)))

    if kind == "provisional":
        if not source:
            raise SpecError("%s: a provisional number still has to say WHY it is a "
                            "guess, so the report can quote it" % key)
        return

    if not source or not str(source).strip():
        raise SpecError(
            "%s has no source. A number with no source does not reach the .dat.\n"
            "  This rule is here because an AI-drawn infographic once handed us\n"
            "  longitud=13200, potencia=2000, vel_max=140, intro_year=2009 - four\n"
            "  confident, plausible, wrong numbers for a train whose real figures are\n"
            "  2200 kW, 120 km/h, 2004. A .pak full of nonsense compiles perfectly.\n"
            "  Give it a URL, a reference measurement, a file:line in the engine, a\n"
            "  formula - or mark it kind='provisional' and it will be listed as a guess."
            % key)

    hit = _SHRUG.search(str(source).strip().lower())
    if hit:
        raise SpecError(
            "%s: %r is not a source, it is a shrug (%r). A model that produces a "
            "number produces it in the same voice whether it read it off the "
            "builder's plate or invented it, and afterwards you cannot tell which - "
            "which is exactly how we nearly built a 2000 kW, 140 km/h Civia. Cite "
            "something a person can go and check, or mark it kind='provisional' and "
            "it will be listed as a guess."
            % (key, source, hit.group(1)))

    if kind == "derived" and not formula:
        raise SpecError("%s is derived, so write the formula down. Arithmetic whose "
                        "workings are lost is a guess wearing a lab coat." % key)


# What a car entry is allowed to say. Anything else is a typo, and a typo here used
# to be silent: the `cars` array was read by nobody, so a misspelt field, a stale
# key or a wrong number sat in the file looking authoritative for months.
#
# bool and int are listed separately on purpose. In Python bool IS an int -
# isinstance(True, int) is True - so a field checked only for int-ness would accept
# "seats": true and add it up as one seat.
_CAR_TYPES = {
    "key": str,          # what the .dat and the couplings are keyed on
    "role": str,         # its letter in the formation
    "name": str,
    "cab": bool,
    "panto": bool,
    "reversed": bool,
    "seats": int,
    "tonnes": int,
    "kilowatts": int,
    "note": str,
}
_CAR_REQUIRED = ("key", "cab", "panto", "reversed")


def _check_car_field(where, field, value):
    want = _CAR_TYPES.get(field)
    if want is None:
        raise SpecError(
            "%s: %r is not a field a car has. The known ones are: %s.\n"
            "  Nothing used to read this array, so a misspelt field was simply a "
            "number that never reached the .dat, silently."
            % (where, field, ", ".join(sorted(_CAR_TYPES))))

    if want is bool:
        if not isinstance(value, bool):
            raise SpecError("%s: %s must be true or false, not %r"
                            % (where, field, value))
    elif want is int:
        # bool first: see _CAR_TYPES. "seats": true must not count as one seat.
        if isinstance(value, bool) or not isinstance(value, int):
            raise SpecError("%s: %s must be a whole number, not %r"
                            % (where, field, value))
        if value < 0:
            raise SpecError("%s: %s cannot be negative (%r)" % (where, field, value))
    elif not isinstance(value, str) or not value.strip():
        raise SpecError("%s: %s must be a non-empty string, not %r"
                        % (where, field, value))


class Spec:
    """The brief. spec.value('speed') gives you a number you can defend."""

    def __init__(self, data, path=None):
        self.path = path
        self.data = data
        self.name = data.get("name")
        if not self.name:
            raise SpecError("the spec needs a name")
        self.pakset = data.get("pakset", "pak128")
        self.facts = {}

        for key, raw in (data.get("facts") or {}).items():
            if not isinstance(raw, dict) or "value" not in raw:
                raise SpecError("%s: write it as {\"value\": ..., \"kind\": ..., "
                                "\"source\": ...}, so the number and its provenance "
                                "cannot be separated" % key)
            kind = raw.get("kind", "measured")
            _check_source(key, kind, raw.get("source"), raw.get("formula"))
            self.facts[key] = Fact(key, raw["value"], kind, raw.get("source"),
                                   raw.get("formula"), raw.get("note"))

        # The unit, in running order. Until now this array was decorative: nothing
        # read it and nothing checked it, which is why the 9000's entries still
        # named cars ("cab_a") that its own module had long since renamed
        # ("m9k_cab_a"), and why a payload split summing to 186 against a measured
        # 178 could ship. Both are load-bearing now.
        self.formation = data.get("formation")
        self.car_totals = data.get("car_totals") or {}
        self.cars = data.get("cars") or []
        self._check_cars()

    def _check_cars(self):
        if not isinstance(self.cars, list):
            raise SpecError("%s: 'cars' must be a list, in running order" % self.name)

        seen = {}
        for i, car in enumerate(self.cars):
            where = "%s car %d" % (self.name, i + 1)
            if not isinstance(car, dict):
                raise SpecError("%s: write each car as an object, not %r"
                                % (where, car))
            for field, value in car.items():
                _check_car_field(where, field, value)
            for field in _CAR_REQUIRED:
                if field not in car:
                    raise SpecError("%s: every car has to say %r" % (where, field))
            key = car["key"]
            if key in seen:
                raise SpecError(
                    "%s: two cars are both called %r (this one and car %d). The key "
                    "is what the .dat and the couplings are keyed on, so a duplicate "
                    "is one car overwriting the other." % (where, key, seen[key] + 1))
            seen[key] = i

        # The formation is the unit's shape written down once. Checking the roles
        # against it checks the car COUNT, the roles themselves and their ORDER in
        # one go - and it is the only place that states what the train actually is.
        if self.formation:
            want = [r.strip() for r in self.formation.split("-")]
            got = [c.get("role") for c in self.cars]
            if None in got:
                raise SpecError("%s declares the formation %s, so every car has to "
                                "say its role" % (self.name, self.formation))
            if got != want:
                raise SpecError(
                    "%s: the cars do not spell the declared formation.\n"
                    "  formation: %-24s (%d cars)\n"
                    "  the cars:  %-24s (%d cars)"
                    % (self.name, "-".join(want), len(want),
                       "-".join(got), len(got)))

        # And the per-car figures meet the sourced totals. This is the whole point:
        # a split is arithmetic over a fact, so it inherits that fact's source - or
        # it is a number nobody can defend, wearing the total's authority.
        for column, fact_key in sorted(self.car_totals.items()):
            if _CAR_TYPES.get(column) is not int:
                raise SpecError("%s: car_totals can only add up a numeric car "
                                "field, and %r is not one" % (self.name, column))
            if fact_key not in self.facts:
                raise SpecError(
                    "%s: car_totals says the %s add up to %r, but there is no such "
                    "fact to check them against." % (self.name, column, fact_key))
            missing = [c["key"] for c in self.cars if column not in c]
            if missing:
                raise SpecError("%s: car_totals adds up the %s, so every car has to "
                                "carry one. These do not: %s"
                                % (self.name, column, ", ".join(missing)))
            total = sum(c[column] for c in self.cars)
            fact = self.facts[fact_key]
            if total != fact.value:
                raise SpecError(
                    "%s: the per-car %s do not add up to %s.\n"
                    "  %s says %s (%s)\n"
                    "  the %d cars carry %s: %s\n"
                    "  A split that does not sum to its total is exactly how the "
                    "9000 shipped 186 seats against a measured 178."
                    % (self.name, column, fact_key, fact_key, fact.value, fact.kind,
                       len(self.cars), total,
                       " + ".join(str(c[column]) for c in self.cars)))

    def car(self, key):
        """One car's entry, by the key the .dat is built under."""
        for car in self.cars:
            if car["key"] == key:
                return car
        raise SpecError("%s: no car called %r. The unit is: %s"
                        % (self.name, key,
                           ", ".join(c["key"] for c in self.cars) or "(empty)"))

    def value(self, key, default=None):
        fact = self.facts.get(key)
        if fact is None:
            if default is not None:
                return default
            raise SpecError("%s: no such fact in the spec for %s. Add it with a "
                            "source, or pass a default." % (key, self.name))
        return fact.value

    def provisional(self):
        """Every guess in the spec, so a report can name them all."""
        return sorted((f for f in self.facts.values() if f.provisional),
                      key=lambda f: f.key)

    def sources(self):
        """{kind: [key, ...]} - the shape of what this spec is built on."""
        out = {}
        for fact in self.facts.values():
            out.setdefault(fact.kind, []).append(fact.key)
        return {k: sorted(v) for k, v in sorted(out.items())}

    def report(self):
        """The lines that go in the build report. Guesses last, and named."""
        lines = []
        for kind in KINDS:
            keys = self.sources().get(kind, [])
            if not keys:
                continue
            lines.append("%s (%d):" % (kind, len(keys)))
            for key in keys:
                f = self.facts[key]
                lines.append("    %-16s %-12s %s"
                             % (key, f.value, f.formula or f.source))
        return lines


def load(path):
    with open(path, encoding="utf-8") as f:
        try:
            data = json.load(f)
        except ValueError as e:
            raise SpecError("%s: not valid JSON: %s" % (path, e))
    return Spec(data, path)
